SET(GAME_SRCS 
    ./game/action/gameaction.h 
    ./game/action/skill/movement.h 
    ./game/action/skill/movement_place.cc 
    ./game/action/skill/movement_place.h 
    ./game/action/skill/movement_step.cc 
    ./game/action/skill/movement_step.h 
    ./game/action/skill/skill.h 
    ./game/action.h 
    ./game/alg/equationalline.cc 
    ./game/alg/equationalline.h 
    ./game/alg/equationallinedouble.cc 
    ./game/alg/equationallinedouble.h 
    ./game/alg/los/cone.cc 
    ./game/alg/los/cone.h 
    ./game/alg/los/evenoctantiterator.cc 
    ./game/alg/los/evenoctantiterator.h 
    ./game/alg/los/octant.cc 
    ./game/alg/los/octant.h 
    ./game/alg/los/octantiterator.h 
    ./game/alg/los/octantprocessor.cc 
    ./game/alg/los/octantprocessor.h 
    ./game/alg/los/oddoctantiterator.cc 
    ./game/alg/los/oddoctantiterator.h 
    ./game/alg/los/processor.cc 
    ./game/alg/los/processor.h 
    ./game/alg.h 
    ./game/base/gamecontroller.cc 
    ./game/base/gamecontroller.h 
    ./game/base/gameobject.cc 
    ./game/base/gameobject.h 
    ./game/base/gamething.h 
    ./game/base/gametile.cc 
    ./game/base/gametile.h 
    ./game/base.h 
    ./game/builder/objectbuilder.cc 
    ./game/builder/objectbuilder.h 
    ./game/builder.h 
    ./game/component/componentbase.h 
    ./game/component/controller.h 
    ./game/component/controller_ai.cc 
    ./game/component/controller_ai.h 
    ./game/component/controller_idle.cc 
    ./game/component/controller_idle.h 
    ./game/component/controller_player.cc 
    ./game/component/controller_player.h 
    ./game/component/damageable.cc 
    ./game/component/damageable.h 
    ./game/component/graphic.cc 
    ./game/component/graphic.h 
    ./game/component/graphic_rectangular.cc 
    ./game/component/graphic_rectangular.h 
    ./game/component/shape.h 
    ./game/component/shape_rectangular.cc 
    ./game/component/shape_rectangular.h 
    ./game/component/vision.cc 
    ./game/component/vision.h 
    ./game/component.h 
    ./game/config.h 
    ./main.cc 
    ./utils/utils.cc 
    ./utils/utils.h 
)
