SET(GAME_SRCS 
    ./game/action/movement.h 
    ./game/action.h 
    ./game/alg/eqline.cc 
    ./game/alg/eqline.h 
    ./game/alg/loscone.cc 
    ./game/alg/loscone.h 
    ./game/alg/losoctant.cc 
    ./game/alg/losoctant.h 
    ./game/alg/losprocessor.cc 
    ./game/alg/losprocessor.h 
    ./game/alg.h 
    ./game/base/gamecontroller.cc 
    ./game/base/gamecontroller.h 
    ./game/base/gameobject.cc 
    ./game/base/gameobject.h 
    ./game/base/gametile.cc 
    ./game/base/gametile.h 
    ./game/base.h 
    ./game/builder.h 
    ./game/builders/objectbuilder.cc 
    ./game/builders/objectbuilder.h 
    ./game/component.h 
    ./game/components/componentbase.h 
    ./game/components/controller.h 
    ./game/components/controller_ai.cc 
    ./game/components/controller_ai.h 
    ./game/components/controller_idle.cc 
    ./game/components/controller_idle.h 
    ./game/components/controller_player.cc 
    ./game/components/controller_player.h 
    ./game/components/damageable.cc 
    ./game/components/damageable.h 
    ./game/components/graphic.cc 
    ./game/components/graphic.h 
    ./game/components/graphic_rectangular.cc 
    ./game/components/graphic_rectangular.h 
    ./game/components/shape.h 
    ./game/components/shape_rectangular.cc 
    ./game/components/shape_rectangular.h 
    ./game/components/vision.cc 
    ./game/components/vision.h 
    ./game/config.h 
    ./main.cc 
    ./utils/utils.cc 
    ./utils/utils.h 
)
